env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CC_TEST_REPORTER_ID=9ada8acb671fdc827dd285f35f2844fb99218d61f8f5e1c4142c1d78e2464bc8
language: ruby
cache: bundler
rvm:
  - 2.5.1
branches:
  only:
    - master
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
script: bundle exec rspec
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
services:
  - postgresql
addons:
  postgresql: "9.2"
  apt:
    packages:
      - postgresql-9.2
      - postgresql-client-9.2
      - postgresql-server-dev-9.2
