env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - CC_TEST_REPORTER_ID=9ada8acb671fdc827dd285f35f2844fb99218d61f8f5e1c4142c1d78e2464bc8
language: ruby
cache: bundler
rvm:
- 2.5.0
branches:
  only:
  - master
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script: bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
services:
- postgresql
addons:
  postgresql: "9.2"
  apt:
    packages:
    - postgresql-9.2
    - postgresql-client-9.2
    - postgresql-server-dev-9.2
deploy:
  provider: heroku
  app: myway-test
  on: master
  api_key:
    secure: SHlvlc4LKwuYTXh5VK2ygNEOQgpURR+G8ZE4umpIzDTWnDsmJzjqquf/WZhGNW6ijIS1RkxMN1jgz97nPzk9Q6NqMM28RfTs7sIalfN5h9Pe3gnmSR0rrnCZC9kulGqGigYiP6qGEimejGmzBqb+mxsM4sbrX5vF5Y292wKesaX+GMYMEOIlJWDzEQeIyKIH6RymOJOLVNGesdOYH3rscyGe2Y/TdH4TPZdg8P8U1MFbEY8d2vhjcd7XCrW+qtp+tI8GkBIY6tyGjp6hBWjLVzOAERkx95WJjhJ7iC1/6pOiHZhGztQ4kX5TnyazG7Oe+x/nkWLJx4jjjXPPikSAhatQNxcbpxyaVheTw6IxYcAc22SZEXY0vHOykKbCLdzdVlOKwaocpvPqCXu5b47PEtT9l3vRXIgONXNySjKGGQ0lm+hYtq/iJ10bI46WnI+K8NgDfB3PsJGQJqDpqz9Blx+vDTkMebZe7tORCFMEOkppDAFLKrzhCEEzeTlOwtcB6izZok5vWbpGz66zccIiwMVt+xTtjgWAmEtp2bgDYHxI+32zu2aPDuUy42d+ivpW7jHBUyjmstjoL2BahWDjh1sYflWKRWQvLL2yMbUZhK1JtsVjU594sT4Wf37HBkDogRn9a9CxS8EVoPzucOhlByr1oAZYjwjSNZLZDt5NpEY=
